version: "3.4"
services:
  nodejs: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 node-22ndtech:debug /bin/sh
    container_name: nodejs
    image: jeff22ndtech/node-22ndtech:debug
    build:
      context: .
      target: debug
    working_dir: /work      #comment out for build.target:prod
    entrypoint: /bin/sh     #comment out for build.target:prod
    stdin_open: true        #comment out for build.target:prod
    tty: true               #comment out for build.target:prod
    volumes:
    - ./src/:/work/src/
    ports:
      - 5002:8080
      - 9229:9229            #debug port
